package render

import (
	"os"
	"strings"

	"github.com/relaygate/relaygate/core/resources"
	"gopkg.in/yaml.v3"
)

// WriteBootstrap writes bootstrap envoy.yaml + nft for xDS mode (no business static listeners/clusters).
func WriteBootstrap(envoyPath, nftPath string, r *resources.Resources, bootOpt BootstrapOptions, renderOpt Options) error {
	cfg, err := RenderBootstrap(r, bootOpt)
	if err != nil {
		return err
	}
	_, nft, err := RenderWith(r, renderOpt)
	if err != nil {
		return err
	}
	if err := resources.EnsureDir(envoyPath); err != nil {
		return err
	}
	if err := resources.EnsureDir(nftPath); err != nil {
		return err
	}
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}
	header := "# Generated by relaygate (xDS bootstrap). Do not edit.\n# Source: DataDir/resources.yaml\n"
	if err := os.WriteFile(envoyPath, append([]byte(header), body...), 0o644); err != nil {
		return err
	}
	if err := os.Chmod(envoyPath, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(nftPath, []byte(nft), 0o644); err != nil {
		return err
	}
	return os.Chmod(nftPath, 0o644)
}

// WriteMergedValidate writes a temporary full-static config for envoy --mode validate.
func WriteMergedValidate(path string, r *resources.Resources, opt Options) error {
	cfg, err := RenderMergedForValidate(r, opt)
	if err != nil {
		return err
	}
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}
	header := "# Generated by relaygate (validate-only merge). Do not edit.\n"
	if err := os.WriteFile(path, append([]byte(header), body...), 0o644); err != nil {
		return err
	}
	return os.Chmod(path, 0o644)
}

// BootstrapOptionsFromEnv builds BootstrapOptions from gateway env + resources meta.
// Local install identity (GATEWAY_NAME / gatewayName arg) always wins over fleet
// YAML meta.gateway_name / gateway.name — otherwise nodes ACK under the wrong
// xDS node id after pulling a package published from the control host.
func BootstrapOptionsFromEnv(gatewayName, xdsPort string, r *resources.Resources) BootstrapOptions {
	node := strings.TrimSpace(gatewayName)
	if node == "" && r != nil {
		node = strings.TrimSpace(r.Meta.GatewayName)
	}
	if node == "" && r != nil {
		node = strings.TrimSpace(r.Gateway.Name)
	}
	if node == "" {
		node = "gateway"
	}
	return BootstrapOptions{
		XDSPort:     ParseXDSPort(xdsPort),
		NodeID:      node,
		NodeCluster: node,
	}
}
