package envoygen

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/robot/proxy/internal/assets"
	"gopkg.in/yaml.v3"
)

func ClusterName(server, protocol string) string {
	return fmt.Sprintf("cluster-%s-%s-game", server, strings.ToLower(protocol))
}

func ListenerName(ruleName string) string {
	return "listener-" + ruleName
}

func Render(r *assets.Resources) (map[string]any, string, error) {
	if err := r.Validate(); err != nil {
		return nil, "", err
	}
	servers := r.ServerMap()
	rules := r.EnabledRules()
	defaults := r.Defaults
	listenAddress := r.Gateway.ListenAddress

	clusters := map[string]any{}
	var listeners []any

	for _, rule := range rules {
		server := servers[rule.Server]
		proto := strings.ToUpper(rule.Protocol)
		cname := ClusterName(server.Name, proto)
		if _, ok := clusters[cname]; !ok {
			if proto == "TCP" {
				clusters[cname] = renderTCPCluster(server, defaults)
			} else {
				clusters[cname] = renderUDPCluster(server, defaults)
			}
		}
		if proto == "TCP" {
			listeners = append(listeners, renderTCPListener(rule, listenAddress, defaults))
		} else {
			listeners = append(listeners, renderUDPListener(rule, listenAddress, defaults))
		}
	}

	clusterList := make([]any, 0, len(clusters))
	names := make([]string, 0, len(clusters))
	for n := range clusters {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		clusterList = append(clusterList, clusters[n])
	}

	cfg := map[string]any{
		"admin": map[string]any{
			"address": map[string]any{
				"socket_address": map[string]any{
					"protocol":   "TCP",
					"address":    r.Meta.AdminAddress,
					"port_value": r.Meta.AdminPort,
				},
			},
			"access_log": []any{
				map[string]any{
					"name": "envoy.access_loggers.file",
					"typed_config": map[string]any{
						"@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
						"path":  "/var/log/envoy/admin-access.log",
					},
				},
			},
		},
		"static_resources": map[string]any{
			"listeners": listeners,
			"clusters":  clusterList,
		},
	}
	return cfg, renderNFT(rules), nil
}

func Write(envoyPath, nftPath string, r *assets.Resources) error {
	cfg, nft, err := Render(r)
	if err != nil {
		return err
	}
	if err := assets.EnsureDir(envoyPath); err != nil {
		return err
	}
	if err := assets.EnsureDir(nftPath); err != nil {
		return err
	}
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}
	header := "# Generated by gateway-render. Do not edit.\n# Source: config/resources.yaml\n"
	if err := os.WriteFile(envoyPath, append([]byte(header), body...), 0o644); err != nil {
		return err
	}
	return os.WriteFile(nftPath, []byte(nft), 0o644)
}

func renderTCPCluster(server assets.Server, d assets.Defaults) map[string]any {
	name := ClusterName(server.Name, "TCP")
	hcPort := server.HealthCheckPort
	if hcPort == 0 {
		hcPort = server.TCPPort
	}
	return map[string]any{
		"name":            name,
		"type":            "STATIC",
		"connect_timeout": "2s",
		"lb_policy":       "ROUND_ROBIN",
		"circuit_breakers": map[string]any{
			"thresholds": []any{
				map[string]any{
					"priority":             "DEFAULT",
					"max_connections":      d.MaxConnections,
					"max_pending_requests": d.MaxPendingRequests,
					"max_requests":         d.MaxConnections,
				},
			},
		},
		"health_checks": []any{
			map[string]any{
				"timeout":             d.HealthCheck.Timeout,
				"interval":            d.HealthCheck.Interval,
				"unhealthy_threshold": d.HealthCheck.UnhealthyThreshold,
				"healthy_threshold":   d.HealthCheck.HealthyThreshold,
				"tcp_health_check":    map[string]any{},
			},
		},
		"load_assignment": map[string]any{
			"cluster_name": name,
			"endpoints": []any{
				map[string]any{
					"lb_endpoints": []any{
						map[string]any{
							"endpoint": map[string]any{
								"address": map[string]any{
									"socket_address": map[string]any{
										"address":    server.Address,
										"port_value": server.TCPPort,
									},
								},
								"health_check_config": map[string]any{
									"port_value": hcPort,
								},
							},
						},
					},
				},
			},
		},
	}
}

func renderUDPCluster(server assets.Server, d assets.Defaults) map[string]any {
	name := ClusterName(server.Name, "UDP")
	return map[string]any{
		"name":            name,
		"type":            "STATIC",
		"connect_timeout": "2s",
		"lb_policy":       "ROUND_ROBIN",
		"circuit_breakers": map[string]any{
			"thresholds": []any{
				map[string]any{
					"priority":        "DEFAULT",
					"max_connections": d.MaxConnections,
				},
			},
		},
		"load_assignment": map[string]any{
			"cluster_name": name,
			"endpoints": []any{
				map[string]any{
					"lb_endpoints": []any{
						map[string]any{
							"endpoint": map[string]any{
								"address": map[string]any{
									"socket_address": map[string]any{
										"address":    server.Address,
										"port_value": server.UDPPort,
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func renderTCPListener(rule assets.Rule, listenAddress string, d assets.Defaults) map[string]any {
	cname := ClusterName(rule.Server, "TCP")
	prefix := strings.ReplaceAll(rule.Name, "-", "_")
	return map[string]any{
		"name": ListenerName(rule.Name),
		"address": map[string]any{
			"socket_address": map[string]any{
				"protocol":   "TCP",
				"address":    listenAddress,
				"port_value": rule.ListenPort,
			},
		},
		"filter_chains": []any{
			map[string]any{
				"filters": []any{
					map[string]any{
						"name": "envoy.filters.network.local_ratelimit",
						"typed_config": map[string]any{
							"@type":       "type.googleapis.com/envoy.extensions.filters.network.local_ratelimit.v3.LocalRateLimit",
							"stat_prefix": "rl_" + prefix,
							"token_bucket": map[string]any{
								"max_tokens":     d.TCPLocalRateLimitBurst,
								"tokens_per_fill": d.TCPLocalRateLimitPerSec,
								"fill_interval":  "1s",
							},
						},
					},
					map[string]any{
						"name": "envoy.filters.network.tcp_proxy",
						"typed_config": map[string]any{
							"@type":       "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
							"stat_prefix": "tcp_" + prefix,
							"cluster":     cname,
							"idle_timeout": d.TCPIdleTimeout,
							"access_log": []any{
								map[string]any{
									"name": "envoy.access_loggers.file",
									"typed_config": map[string]any{
										"@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
										"path":  "/var/log/envoy/tcp-access.json",
										"log_format": map[string]any{
											"json_format": map[string]any{
												"ts":          "%START_TIME%",
												"rule":        rule.Name,
												"protocol":    "TCP",
												"downstream":  "%DOWNSTREAM_REMOTE_ADDRESS%",
												"upstream":    "%UPSTREAM_HOST%",
												"bytes_rx":    "%BYTES_RECEIVED%",
												"bytes_tx":    "%BYTES_SENT%",
												"duration_ms": "%DURATION%",
												"flags":       "%RESPONSE_FLAGS%",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func renderUDPListener(rule assets.Rule, listenAddress string, d assets.Defaults) map[string]any {
	cname := ClusterName(rule.Server, "UDP")
	prefix := strings.ReplaceAll(rule.Name, "-", "_")
	return map[string]any{
		"name": ListenerName(rule.Name),
		"address": map[string]any{
			"socket_address": map[string]any{
				"protocol":   "UDP",
				"address":    listenAddress,
				"port_value": rule.ListenPort,
			},
		},
		"udp_listener_config": map[string]any{
			"downstream_socket_config": map[string]any{
				"max_rx_datagram_size": 1500,
			},
		},
		"listener_filters": []any{
			map[string]any{
				"name": "envoy.filters.udp_listener.udp_proxy",
				"typed_config": map[string]any{
					"@type":       "type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig",
					"stat_prefix": "udp_" + prefix,
					"idle_timeout": d.UDPIdleTimeout,
					"matcher": map[string]any{
						"on_no_match": map[string]any{
							"action": map[string]any{
								"name": "route",
								"typed_config": map[string]any{
									"@type":   "type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route",
									"cluster": cname,
								},
							},
						},
					},
					"upstream_socket_config": map[string]any{
						"max_rx_datagram_size": 1500,
					},
				},
			},
		},
	}
}

func renderNFT(rules []assets.Rule) string {
	tcpSet := map[int]struct{}{}
	udpSet := map[int]struct{}{}
	for _, r := range rules {
		switch strings.ToUpper(r.Protocol) {
		case "TCP":
			tcpSet[r.ListenPort] = struct{}{}
		case "UDP":
			udpSet[r.ListenPort] = struct{}{}
		}
	}
	tcp := sortedPorts(tcpSet)
	udp := sortedPorts(udpSet)
	if len(tcp) == 0 {
		tcp = []int{10001}
	}
	if len(udp) == 0 {
		udp = []int{10001}
	}
	return fmt.Sprintf(`# Generated by gateway-render. Do not edit.
# TCP game ports
define GAME_TCP_PORTS = { %s }
# UDP game ports
define GAME_UDP_PORTS = { %s }
`, joinInts(tcp), joinInts(udp))
}

func sortedPorts(set map[int]struct{}) []int {
	out := make([]int, 0, len(set))
	for p := range set {
		out = append(out, p)
	}
	sort.Ints(out)
	return out
}

func joinInts(ports []int) string {
	parts := make([]string, len(ports))
	for i, p := range ports {
		parts[i] = fmt.Sprintf("%d", p)
	}
	return strings.Join(parts, ", ")
}

func Summarize(r *assets.Resources) string {
	servers := r.ServerMap()
	rules := r.EnabledRules()
	var b strings.Builder
	fmt.Fprintf(&b, "校验通过: %d 台服务器, %d 条启用规则\n", len(servers), len(rules))
	for _, rule := range rules {
		fmt.Fprintf(&b, "  - %s: %s/%d -> %s (%s)\n",
			rule.Name, strings.ToUpper(rule.Protocol), rule.ListenPort, rule.Server, rule.Kind)
	}
	return b.String()
}
